---
- hosts: localhost
  gather_facts: no
  vars:
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    gcp_project: proxy-274119
    gcp_cred_kind: serviceaccount
    # to take here https://console.cloud.google.com/apis/credentials/serviceaccountkey
    gcp_cred_file: /Users/u16705009/Downloads/proxy-274119-67ad9bb16345.json
    my_user: rebaxis
    my_user_open_key:
      "{{ my_user }}: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4tTNQz9p5ecYeFGToZ/JPKCD5id1NQhvZJAr1ArORQSQB1Nm2vck4i0jj/80wJ\
      +nbnFwYTFcXbdAmuv7TltVPfJBsqV8GYr+gUkXuVaNf4Ov8hmbC+ubeJvc229XaKKevbk0qeivAL1qg+B3ZLd5b2L8XBJG3c2aeT9MQrFHyAty\
      Y9Ty74vGtpgeVadK83YIcRAfuQlDVKH7rkv+d3Jt1iGGgfVKPmV3X9wYqfbWeskXjOxhKoiKv8Xzds8ipl9wGiV6FBrJWJGxptORYPPFZDW1Ri\
      Tm4DO1A9zoNSAW2BwZweeqZW0cSJdk8SKL4Ss6QYHyoClocOMfrgP6EE5vN rebaxis@gmail.com"
    image: 'projects/centos-cloud/global/images/centos-7-v20190116'
    open_ports: ['443','22','3128']
    # the Netherlands
    address_region: europe-west4
    instance_zone: europe-west4-c
    # Vegas
    #address_region: us-west4
    #instance_zone: us-west4-a

  tasks:
  - name: create instance
    import_role:
      name: GCP
      tasks_from: create_instance

- hosts: instance
  vars:
    - ansible_ssh_extra_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  vars_prompt:
    - name: "user"
      prompt: "user for squid"
      private: no
    - name: "pass"
      prompt: "pass for user"
      private: yes
      confirm: yes

  tasks:
    - name: install proxy
      import_role:
        name: squid
